services:
  hayhooks:
    build: .
    container_name: hayhooks
    ports:
      - '1416:1416'
    volumes:
      - ./pipelines:/opt/pipelines
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:1416/status || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3